### ISSUE TITLE
Generate Source Mapping Error when a property value contains comma

### ISSUE THREAD

**Issue by rikuayanokozy** [google/closure-stylesheets#11] opened 2015-06-26 09:22 UTC
**What steps will reproduce the problem?**
1.Clone the latest closure-stylesheets and compile
2.specify output-source-map when building gss

	java -jar build/closure-stylesheets.jar --allow-unrecognized-properties --output-renaming-map-format CLOSURE_UNCOMPILED --rename CLOSURE --output-renaming-map renaming_map.js --output-source-map test.source.map --output-file test.css test.gss

**What is the expected output? What do you see instead?**
I got an error:
> Compiler internal error: null
> java.lang.IllegalStateException
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:133)
>         at com.google.common.css.compiler.passes.DefaultGssSourceMapGenerator.endSourceMapping(DefaultGssSourceMapGenerator.java:157)
>         at com.google.common.css.compiler.passes.CodePrinter.leave(CodePrinter.java:103)
>         at com.google.common.css.compiler.passes.UniformVisitor.leaveImportBlock(UniformVisitor.java:266)
>         at com.google.common.css.compiler.ast.DefaultVisitController$RootVisitImportBlockState.doVisit(DefaultVisitController.java:387)
>         at com.google.common.css.compiler.ast.DefaultVisitController.startVisit(DefaultVisitController.java:2028)
>         at com.google.common.css.compiler.passes.CompactPrinter.runPass(CompactPrinter.java:473)
>         at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.parseAndPrint(DefaultCommandLineCompiler.java:127)
>         at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.compile(DefaultCommandLineCompiler.java:110)
>         at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.execute(DefaultCommandLineCompiler.java:149)
>         at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.executeJob(ClosureCommandLineCompiler.java:335)
>         at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.main(ClosureCommandLineCompiler.java:400)

**What version of the product are you using? On what operating system?**
Latest clone from github, mac os x and java 1.8

**Please provide any additional information below.**
I generated a gss file that contains comma in the property value and enable output-source-map both, then closure stylesheets throw an exception above.
i also generated a gss file(test2.gss) that not contains comma in the property value, then compile it using same parameter, it works fine.

**test.gss:**
>.test {
>	font-family: Helvetica, Tahoma;
>}

**test2.gss**
>.test2 {
>	font-family: Helvetica;
>}

**Comment by iflan** [comment] 2015-06-26 11:54
Excellent bug report. I will take a look.

**Comment by hochhaus** [comment] 2016-09-06 04:13
This bug is causing problems for me too. For example:

```
@font-face {                                                                    
  font-family: 'Roboto';                                                        
  font-style: normal;                                                           
  font-weight: 400;                                                             
  src: local('Roboto'), local('Roboto-Regular'),                                
       url('/roboto.woff2') format('woff2'),                                    
       url('/roboto.woff') format('woff');                                      
}                                                                               
                                                                                
body {                                                                          
  font-family: 'Roboto', sans-serif;                                            
  color: #555;                                                                  
}
```

When run with the 1.3.0 compiler:

```bazel-out/local-fastbuild/bin/external/io_bazel_rules_closure/third_party/java/csscomp/ClosureCommandLineCompiler --output-file bazel-out/local-fastbuild/bin/lathamlabs/ll_css_bin.css --output-source-map bazel-out/local-fastbuild/bin/lathamlabs/ll_css_bin.css.map --input-orientation LTR --output-orientation NOCHANGE --output-renaming-map bazel-out/local-fastbuild/bin/lathamlabs/ll_css_bin.css.js --output-renaming-map-format CLOSURE_COMPILED_SPLIT_HYPHENS --rename CLOSURE lathamlabs/ll.css```

Results in the following compiler internal error:

```
Compiler internal error: null
java.lang.NullPointerException
        at com.google.debugging.sourcemap.SourceMapGeneratorV3$MappingTraversal.isOverlapped(SourceMapGeneratorV3.java:737)
        at com.google.debugging.sourcemap.SourceMapGeneratorV3$MappingTraversal.traverse(SourceMapGeneratorV3.java:693)
        at com.google.debugging.sourcemap.SourceMapGeneratorV3.prepMappings(SourceMapGeneratorV3.java:577)
        at com.google.debugging.sourcemap.SourceMapGeneratorV3.appendTo(SourceMapGeneratorV3.java:363)
        at com.google.common.css.compiler.passes.DefaultGssSourceMapGenerator.appendOutputTo(DefaultGssSourceMapGenerator.java:120)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.execute(DefaultCommandLineCompiler.java:185)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.executeJob(ClosureCommandLineCompiler.java:342)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.main(ClosureCommandLineCompiler.java:408)
```

After removing the commas (eg: `font-family: 'Roboto';` vs `font-family: 'Roboto', sans-serif;`) the compiler works correctly.

**Comment by mikesamuel** [comment] 2016-09-06 18:18
For reference, here are links to source code

* [SourceMapGeneratorV3.java:737](https://github.com/google/closure-compiler/blob/b8d8d1d6c6d245a3df57feedc511f2e849b01932/src/com/google/debugging/sourcemap/SourceMapGeneratorV3.java#L737)
* [SourceMapGeneratorV3.java:693](https://github.com/google/closure-compiler/blob/b8d8d1d6c6d245a3df57feedc511f2e849b01932/src/com/google/debugging/sourcemap/SourceMapGeneratorV3.java#L693)
* [SourceMapGeneratorV3.java:577](https://github.com/google/closure-compiler/blob/b8d8d1d6c6d245a3df57feedc511f2e849b01932/src/com/google/debugging/sourcemap/SourceMapGeneratorV3.java#L577)
* [SourceMapGeneratorV3.java:363](https://github.com/google/closure-compiler/blob/b8d8d1d6c6d245a3df57feedc511f2e849b01932/src/com/google/debugging/sourcemap/SourceMapGeneratorV3.java#L363)
* [DefaultGssSourceMapGenerator.java:120](https://github.com/google/closure-stylesheets/blob/d4476e5295f20780cf453df8e534ceeae991fcb9/src/com/google/common/css/compiler/passes/DefaultGssSourceMapGenerator.java#L120)

And the prior one

* [DefaultGssSourceMapGenerator.java:157](https://github.com/google/closure-stylesheets/blob/d4476e5295f20780cf453df8e534ceeae991fcb9/src/com/google/common/css/compiler/passes/DefaultGssSourceMapGenerator.java#L157)

**Comment by hochhaus** [comment] 2016-09-12 06:56
@iflan Do you have any time to look more at this bug?

**Comment by iflan** [comment] 2016-09-13 14:27
I will look at this tomorrow. Sorry for the delay!

**Comment by hochhaus** [comment] 2016-09-13 14:29
Thanks.

**Comment by iflan** [comment] 2016-09-14 17:13
As expected, it looks like we're not generating the right end position sometimes:

![screen shot 2016-09-14 at 7 09 36 pm](https://cloud.githubusercontent.com/assets/7514156/18522060/cf858c9e-7aae-11e6-9af6-f2ecc37cb604.png)

I'm still looking at this. When I find a solution, I'll post a quick patch, but make a better patch, test, etc. and submit it internally which may take a few more days.

Thanks for your patience.

**Comment by hochhaus** [comment] 2016-09-14 17:37
Thanks Ian. Once the final patch is merged and pushed to the open source repo could a new release be cut?

**Comment by mikesamuel** [comment] 2016-09-14 17:47
https://github.com/google/closure-stylesheets/blob/c72069d15650773a9df1bbb6ef911afac29ec03d/src/com/google/common/css/compiler/passes/FixupFontDeclarations.java#L528-L530 looks dodgy.

It seems to be taking the location of the first font family as the location of a bunch of font families.

**Comment by iflan** [comment] 2016-09-14 19:15
That's a good guess, but I don't think that's it. My debugging has lead me to a problem in the `DefaultVisitController`. For some reason, `UniformVisitor` is not always having the `leave` method called for each enter for `CssCompositeValueNode`s.

**Comment by iflan** [comment] 2016-09-14 19:56
OK, I'm pretty sure that the problem is that none of the methods in `CompactPrinter` that come from `UniformVisitor` actually call their `super()`. I'm surprised that nothing else broke, but that could explain a lot of our problems with sourcemaps.

That's a big change, so I'll tackle it tomorrow.

**Comment by iflan** [comment] 2016-09-15 07:38
After investigation, I have a patch (below) that avoids the NPE as originally described. It's not the right solution because further subclasses of `CompactPrinter` will end up having the same problem. They *can't* call their `super` methods because that would trigger whatever behavior they are trying to override.

The solution is (I think) to:
* split `CompactPrinter`'s `CssCompilerPass` and `CodePrinter` logic into separate classes;
* remove `CodePrinter` from the `*Printer` class hierarchy;
* change `CodePrinter` to a pure visitor and call it something like `SourceMapVisitor`;
* create a delegating visitor that calls the `enter*` methods of several other visitors in order and the `leave*` methods in the opposite order;
* change the various `*Printer` classes to use the delegating visitor to generate sourcemaps.

I'm going to try to start on this change today, but in the meantime this patch should help:

[0001-Fix-CompactPrinter-to-call-super-methods.patch.txt](https://github.com/google/closure-stylesheets/files/474053/0001-Fix-CompactPrinter-to-call-super-methods.patch.txt)

Note that this patch *won't* be part of the next release. Instead, it will have the correct solution as outlined above. (And, yes, we will make the new release as soon as the fix is pushed out to GitHub.)

**Comment by hochhaus** [comment] 2016-09-15 07:44
Awesome. Thanks Ian.

**Comment by iflan** [comment] 2016-09-16 16:41
I've got a change internally that works. However, it's pretty big and complicated. My main reviewer is on vacation, so I've asked @mikesamuel to take a look. Unfortunately, this may take a few more days to get in and pushed out.

**Comment by hochhaus** [comment] 2016-09-16 17:05
Thanks. No worries about a delay. As long as a fix is slowly moving through the pipeline that meets my needs.

**Comment by iflan** [comment] 2016-09-20 15:53
Just an update on this: I'm currently getting this submitted internally and it should be done tonight. I'm not going to have time to push out a new release tonight, so I'm expecting to push it tomorrow morning. (The Maven release may be delayed until tomorrow night, though.)

**Comment by hochhaus** [comment] 2016-09-20 16:15
Awesome. Thanks for providing the timeline.

**Closed** 2016-09-21 08:15 UTC
Labels: bug

**Comment by iflan** [comment] 2016-09-21 13:25
A new release, [v1.4.0], has been pushed. It's available on [GitHub] and [Maven Central].

[v1.4.0]: https://github.com/google/closure-stylesheets/tree/v1.4.0
[GitHub]: https://github.com/google/closure-stylesheets/releases/tag/v1.4.0
[Maven Central]: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.closure-stylesheets%22%20AND%20a%3A%22closure-stylesheets%22

**Comment by hochhaus** [comment] 2016-09-21 16:14
Thanks Ian!
