### ISSUE TITLE
Defining and calling mixins from separate files causes "Compiler internal error"

### ISSUE THREAD

**Issue by hochhaus** [google/closure-stylesheets#70] opened 2015-11-03 19:59 UTC
When defining and calling a mixin in separate source files the compiler currently (both 1.0 and HEAD) result in a "Compiler internal error". However, this did not used to be the case. A compiler that I build on Dec 23 2014 compiles these inputs just fine.

```
ahochhaus@ahochhaus-pc:~/test$ cat def.gss 
@defmixin spriteUrl() {
  background: url('sprite.png') no-repeat;
}
ahochhaus@ahochhaus-pc:~/test$ cat call.gss 
.example {
  @mixin spriteUrl();
}
ahochhaus@ahochhaus-pc:~/test$ java -jar closure-stylesheets.jar def.gss call.gss
Compiler internal error: com.google.common.css.compiler.ast.CssMixinNode cannot be cast to com.google.common.css.compiler.ast.CssDeclarationNode
java.lang.ClassCastException: com.google.common.css.compiler.ast.CssMixinNode cannot be cast to com.google.common.css.compiler.ast.CssDeclarationNode
        at com.google.common.css.compiler.passes.DisallowDuplicateDeclarations.enterRuleset(DisallowDuplicateDeclarations.java:69)
        at com.google.common.css.compiler.ast.DefaultVisitController$VisitRulesetState.doVisit(DefaultVisitController.java:875)
        at com.google.common.css.compiler.ast.DefaultVisitController.startVisit(DefaultVisitController.java:2028)
        at com.google.common.css.compiler.passes.DisallowDuplicateDeclarations.runPass(DisallowDuplicateDeclarations.java:80)
        at com.google.common.css.compiler.passes.PassRunner.runPasses(PassRunner.java:147)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.parseAndPrint(DefaultCommandLineCompiler.java:130)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.compile(DefaultCommandLineCompiler.java:116)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.execute(DefaultCommandLineCompiler.java:157)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.executeJob(ClosureCommandLineCompiler.java:335)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.main(ClosureCommandLineCompiler.java:400)
ahochhaus@ahochhaus-pc:~/test$ cat def.gss call.gss > combined.gss
ahochhaus@ahochhaus-pc:~/test$ java -jar closure-stylesheets.jar combined.gss 
.example{background:url('sprite.png') no-repeat}
ahochhaus@ahochhaus-pc:~/test$ java -jar closure-stylesheets-20141223.jar def.gss call.gss 
.example{background:url('sprite.png') no-repeat}
```

**Comment by hochhaus** [comment] 2015-11-03 20:53
I built a few versions of the stylesheets compiler. As best I can tell this code works in (2fd63e3d5a7a73def76079b43e73a3638aa7d11a) and fails after (a4397232982dc60b0e0fe3d627ac0e1de1663048).

**Comment by iflan** [comment] 2015-11-04 09:30
I confirmed this with:
```
git bisect start
git bisect bad
git bisect good 2fd63e3d5a7a73def76079b43e73a3638aa7d11a
git bisect run /bin/bash -c "ant && java -jar build/closure-stylesheets.jar ../def.gss ../call.gss"
```
I've looked through that change. The only thing that jumped out at me was the [addition of the `allowDefPropagation` field][1] in `JobDescription`. I think that may have caused the issue because, as far as I can see, there is no flag to actually turn that on.

I'm going to add a test and fix for this internally, then push it back out.

Thanks for your excellent bug report!

[1]: https://github.com/google/closure-stylesheets/commit/a4397232982dc60b0e0fe3d627ac0e1de1663048#diff-33233da4d610eda872a1d1af540b801fR49

**Comment by iflan** [comment] 2015-11-04 10:45
BTW, there are actually two errors wrapped up in the same bug.

1.  The `allowDefPropagation` field is false, meaning that mixins defined in one file can't be used in other files. This should print the error:

    ```
    The name of the mixin matches no mixin definition name in call.gss at line 1 column 12:
    .example { @mixin spriteUrl(); }
               ^
    ```

2.  The `java.lang.ClassCastException` causes the parser to exit before the error can be printed.

I've got a fix for (1) that will allow `@def` and `@mixin`s to propagate by default. It's going to take a bit more work to make fatal errors still report the errors that happened first.

**Comment by hochhaus** [comment] 2015-11-04 16:55
Thanks for the prompt reply. Even just fixing (1) allowDefPropagation by default [or with a flag] is good enough for me. The error reporting is far less important from my perspective.

**Comment by iflan** [comment] 2015-11-04 19:24
This should be fixed.

**Closed by iflan** 2015-11-04 19:24 UTC

**Comment by hochhaus** [comment] 2015-11-04 22:49
Thanks! I can confirm that your change resolves my issue.
